In [15]:
import numpy as np

class ART1:
    def __init__(self, n_features, vigilance=0.5):
        self.n_features = n_features
        self.vigilance = vigilance
        self.weights = []

    def _similarity(self, x, w):
        return np.sum(np.minimum(x, w)) / (np.sum(x) + 1e-9)

    def fit(self, X):
        for x in X:
            assigned = False
            for i, w in enumerate(self.weights):
                sim = self._similarity(x, w)
                if sim >= self.vigilance:
                    self.weights[i] = np.minimum(w, x)
                    assigned = True
                    break
            if not assigned:
                self.weights.append(x.copy())

    def predict(self, X):
        labels = []
        for x in X:
            sims = [self._similarity(x, w) for w in self.weights]
            labels.append(np.argmax(sims))
        return labels

X = np.array([
    [1, 1, 0, 0],
    [1, 0, 0, 0],
    [0, 1, 0, 0],
    [0, 0, 1, 1],
    [0, 0, 1, 0],
    [0, 0, 0, 1]
])

art = ART1(n_features=4, vigilance=0.6)
art.fit(X)
labels = art.predict(X)

print("Input Data:\n", X)
print("Cluster Labels:", labels)
print("Number of Clusters:", len(art.weights))

Input Data:
 [[1 1 0 0]
 [1 0 0 0]
 [0 1 0 0]
 [0 0 1 1]
 [0 0 1 0]
 [0 0 0 1]]
Cluster Labels: [np.int64(0), np.int64(0), np.int64(1), np.int64(2), np.int64(2), np.int64(3)]
Number of Clusters: 4
